# Generated by Django 4.1.13 on 2024-02-20 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="Описание работы", verbose_name="Подробное описание работы"
            ),
        ),
    ]
